/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 web.gltf --transform 
Files: web.gltf [502.69KB] > /Users/harshvardhansinghchauhan/Downloads/blender/3d_clipart_-_webdev/web-transformed.glb [252.53KB] (50%)
Author: Helindu (https://sketchfab.com/Helindu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-clipart-webdev-f3d8f1a7174847d994ab698e265f9672
Title: 3D Clipart - WebDev
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/web-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.JS_text001_0.geometry} material={materials.PaletteMaterial001} position={[3.767, -0.071, 0.509]} />
    </group>
  )
}

useGLTF.preload('/web-transformed.glb')
